export const soupProducts = [
  {
    name: 'Суп Том Ям',
    description: 'Острый тайский суп с креветками, кокосовым молоком и лаймом.',
    image: require('../assets/soup_1.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Куриный Суп с Рисом',
    description: 'Легкий куриный суп с рисом и ароматными специями.',
    image: require('../assets/soup_2.jpg'),
    price: 15,
    count: 1,
  },
  {
    name: 'Фо Бо',
    description: 'Вьетнамский суп с говядиной, рисовой лапшой и травами.',
    image: require('../assets/soup_3.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Суп Мисо',
    description: 'Традиционный японский суп с водорослями и тофу.',
    image: require('../assets/soup_4.jpg'),
    price: 18,
    count: 1,
  },
  {
    name: 'Гороховый Суп',
    description: 'Сытный суп из зеленого горошка с копченостями.',
    image: require('../assets/soup_5.jpg'),
    price: 14,
    count: 1,
  },
  {
    name: 'Суп Лакса',
    description:
      'Пряный малайзийский суп с лапшой, кокосовым молоком и курицей.',
    image: require('../assets/soup_6.jpg'),
    price: 21,
    count: 1,
  },
  {
    name: 'Рыбный Суп',
    description: 'Суп из свежей рыбы с зеленью и специями.',
    image: require('../assets/soup_7.jpg'),
    price: 19,
    count: 1,
  },
  {
    name: 'Суп из Белых Грибов',
    description: 'Ароматный суп с лесными грибами и картофелем.',
    image: require('../assets/soup_8.jpg'),
    price: 17,
    count: 1,
  },
  {
    name: 'Хашлама',
    description: 'Наваристый суп с бараниной, овощами и зеленью.',
    image: require('../assets/soup_9.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Окрошка на Айране',
    description: 'Холодный суп с овощами и курицей на основе айрана.',
    image: require('../assets/soup_10.jpg'),
    price: 14,
    count: 1,
  },
  {
    name: 'Тыквенный Суп с Имбирем',
    description: 'Нежный суп из тыквы с добавлением имбиря и специй.',
    image: require('../assets/soup_11.jpg'),
    price: 16,
    count: 1,
  },
  {
    name: 'Бульон с Пельменями',
    description: 'Прозрачный бульон с небольшими пельменями.',
    image: require('../assets/soup_12.jpg'),
    price: 15,
    count: 1,
  },
  {
    name: 'Суп Кимчи',
    description: 'Корейский суп с квашеной капустой кимчи и тофу.',
    image: require('../assets/soup_13.jpg'),
    price: 18,
    count: 1,
  },
  {
    name: 'Щавелевый Суп',
    description: 'Кисло-сладкий суп со щавелем, яйцом и картофелем.',
    image: require('../assets/soup_14.jpg'),
    price: 14,
    count: 1,
  },
  {
    name: 'Французский Буйабес',
    description: 'Суп из морепродуктов с ароматом прованских трав.',
    image: require('../assets/soup_15.jpg'),
    price: 25,
    count: 1,
  },
  {
    name: 'Суп из Красной Фасоли',
    description: 'Пикантный суп из фасоли с овощами и зеленью.',
    image: require('../assets/soup_16.jpg'),
    price: 14,
    count: 1,
  },
  {
    name: 'Крем-Суп из Цветной Капусты',
    description: 'Сливочный суп с цветной капустой и сыром.',
    image: require('../assets/soup_17.jpg'),
    price: 15,
    count: 1,
  },
  {
    name: 'Морковный Суп с Апельсином',
    description: 'Нежный суп из моркови с цитрусовыми нотками.',
    image: require('../assets/soup_18.jpg'),
    price: 14,
    count: 1,
  },
  {
    name: 'Крем-Суп из Зеленого Горошка',
    description: 'Суп-пюре из зеленого горошка с мятой и сливками.',
    image: require('../assets/soup_19.jpg'),
    price: 15,
    count: 1,
  },
  {
    name: 'Томатный Суп с Морепродуктами',
    description: 'Кисло-сладкий суп из томатов с креветками и мидиями.',
    image: require('../assets/soup_20.jpg'),
    price: 22,
    count: 1,
  },
];
